<?xml version="1.0" encoding="UTF-8"?>
<!-- A four wheel robot -->
<!-- 
    A four wheel mobile robot made for Tutorial 3 (for being spawned in gazebo)
-->
<robot name="fw_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Include other files -->
    <!-- Include the properties file -->
    <xacro:include filename="$(find basic_robotics)/urdf/fwb_parameters_t4.xacro" />
    <!-- Include headers (XACRO macros) file  -->
    <xacro:include filename="$(find basic_robotics)/urdf/fwb_macros.xacro" />
    <!-- Include file for Gazebo (general items) -->
    <xacro:include filename="$(find basic_robotics)/urdf/fwb_t4_general.gazebo" />
    <!-- Include the XACRO for camera -->
    <xacro:include filename="$(find basic_robotics)/urdf/fwb_camera_t4.xacro" />
    <!-- Include the XACRO for LidarScanner -->
    <xacro:include filename="$(find basic_robotics)/urdf/fwb_lidar_t4.xacro" />

    <!-- Main code -->
    <link name="dummy">
        <!-- 
            This is a dummy link for KDL to parse the URDF. Basically, a
            root link with <inertia> is not supported by KDL [1] (a library
            used by robot_state_publisher). Reference at [2]

            [1]: https://www.orocos.org/kdl.html
            [2]: https://answers.ros.org/question/192817/error-msg-the-root-link_base-has-an-inertia-specified-in-the-urdf-but-kdl/
        -->
    </link>
    <!-- Main body link -->
    <link name="body">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="${body_m}"/>
            <xacro:inertia_cuboid m="${body_m}" sx="${body_sx}" sy="${body_sy}" sz="${body_sz}" />
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${body_sx} ${body_sy} ${body_sz}"/>
            </geometry>
        </visual>
        <collition>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${body_sx} ${body_sy} ${body_sz}"/>
            </geometry>
        </collition>
    </link>
    <!-- Attach the dummy link -->
    <joint name="dummy_body_fixed" type="fixed">
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        <parent link="dummy" />
        <child link="body" />
    </joint>
    <!-- Attach the wheels -->
    <xacro:add_wheel lname="fl_wheel" jname="fl_wheel_joint" 
        sx="${body_sx/2}" sy="${(body_sy + wheel_h)/2}" sz="${-body_sz/2}"
        m="${wheel_m}" r="${wheel_r}" h="${wheel_h}"/>  <!-- Front Left -->
    <xacro:add_wheel lname="fr_wheel" jname="fr_wheel_joint" 
        sx="${body_sx/2}" sy="${-(body_sy + wheel_h)/2}" sz="${-body_sz/2}"
        m="${wheel_m}" r="${wheel_r}" h="${wheel_h}"/>  <!-- Front Right -->
    <xacro:add_wheel lname="hl_wheel" jname="hl_wheel_joint" 
        sx="${-body_sx/2}" sy="${(body_sy + wheel_h)/2}" sz="${-body_sz/2}"
        m="${wheel_m}" r="${wheel_r}" h="${wheel_h}"/>  <!-- Hind Left -->
    <xacro:add_wheel lname="hr_wheel" jname="hr_wheel_joint" 
        sx="${-body_sx/2}" sy="${-(body_sy + wheel_h)/2}" sz="${-body_sz/2}"
        m="${wheel_m}" r="${wheel_r}" h="${wheel_h}"/>  <!-- Hind Right -->
</robot>
